# Generated by Django 4.1.2 on 2022-10-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
                ('kraj', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
        migrations.AddField(
            model_name='osoba',
            name='druzyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.druzyna'),
        ),
    ]
